- nft_ingester/src/program_transformers/token/mod.rs
- nft_ingester/src/program_transformers/token_metadata/v1_asset.rs
Geyser won't pass in closed accounts, so when a token account is closed, its state is not changed in the token_accounts table. This results in multiple token_accounts having an amount of 1. 
This breaks when we reindex the metadata account, it assumed that there would be 1 token_account with the mint with balance 1. If there are multiple it might pick the wrong owner of the asset.
Solution is to query for the token_account row with the latest slot_updated. Closed accounts will not be indexed so their slot_updated will always be older, and querying for latest slot will always get the valid token_account.
> Closed token account bug

- das_api/src/api/api_impl.rs
- das_api/src/config.rs
- digital_asset_types/src/dapi/assets_by_authority.rs
- digital_asset_types/src/dapi/assets_by_creator.rs
- digital_asset_types/src/dapi/assets_by_group.rs
- digital_asset_types/src/dapi/assets_by_owner.rs
- digital_asset_types/src/dapi/common/asset.rs
- digital_asset_types/src/dapi/get_asset.rs
- digital_asset_types/src/dapi/search_assets.rs
- digital_asset_types/src/rpc/mod.rs
- digital_asset_types/src/rpc/transform.rs
- digital_asset_types/tests/data/infinite_fungi.json
- digital_asset_types/tests/data/mad_lad.json
- digital_asset_types/tests/json_parsing.rs
Add CDN support (optional). Sort so image url is provided first in files (makes it easier for explorers) to display the right image (e.g. show mad lad instead of rug).
Testing: 
* Locally against claynos, madlads, and 1/1 nfts. 
* Verified that CDN transform is applied with and without the env var.
> feat(api): add cdn support

- das_api/src/api/mod.rs
For example, this is the output 
```
{
"jsonrpc": "2.0",
"error": {
"code": -32602,
"message": "unknown field `only_verified`, expected one of `creatorAddress`, `onlyVerified`, `sortBy`, `limit`, `page`, `before`, `after` at line 3 column 23"
},
"id": "0"
}
```
Note, this could be a breaking change if the users are using the API with unknown feilds.
> DAS-API: Reject requests if the fields are unknown

- nft_ingester/src/program_transformers/bubblegum/burn.rs
- nft_ingester/src/program_transformers/bubblegum/db.rs
* Burns were failing to parse and breaking trees.
* The issue is that the burn ix does not include the leaf schema like other txns.
* Burn ix: https://github.com/metaplex-foundation/metaplex-program-library/blob/master/bubblegum/program/src/lib.rs#L1296
* Compared to a transfer, which includes leaf schema via the application data function: https://github.com/metaplex-foundation/metaplex-program-library/blob/master/bubblegum/program/src/lib.rs#L1232
* The outcome is that `parsing_result.leaf_update` was always empty and no indexing happened.
* The fix is to derive the necessary data from the tree update instead.
* Locally against tree with broken nft indexing (txn example: 4nmSHdMHAS7gKqYDt3fP8MSKK9XE2Qfg8HuZWTw1d9xwkJjQ94WmAoNKDAaaqMLRBdPRw4VpedpQJ9ZMm35MZh6B)
> fix(ingester): fix compressed nft burn indexing

- digital_asset_types/src/dapi/common/asset.rs
- digital_asset_types/src/rpc/asset.rs
Nonce can be null, but we always cast it zero.
Tested: Local
> fix(api): fix bad edition nonce conversions in api

- digital_asset_types/src/dapi/common/asset.rs
- digital_asset_types/src/rpc/asset.rs
Tested locally against all endpoints, both burned and non-burned cNFTs.
> feat(api): expose burnt field

- tools/tree-status/README.md
- tools/tree-status/src/main.rs
-   Fix some bugs with the fix-tree tool.
-   Add concurrency configuration
-   Ran it locally.
> fix(tools): fix the fix-tree tool

- digital_asset_types/src/dao/scopes/asset.rs
-   Secondary ordering by asset `id` to make the ordering consistent and deterministic
-   Testing performed locally
> fix: make sort order deterministic

- digital_asset_types/src/dao/scopes/asset.rs
-   Use user-provided sort direction for secondary sorting by `id`, instead of just `ASC`
-   Testing performed locally
> fix: use user-provided sort direction

- das_api/src/api/api_impl.rs
- das_api/src/api/mod.rs
-   Previously, `delegate` used to be `Vec<u8>`, but in practice it should be a `String` so that users can provide a valid address.
> fix: make `delegate` string

- nft_ingester/Cargo.lock
- nft_ingester/src/account_updates.rs
- nft_ingester/src/metrics.rs
- nft_ingester/src/transaction_notifications.rs
-   After adding some new metrics we were accidentally ACKing retryable errors, preventing retries. Note that retries were also broken in the redis messenger. These are fixed here: https://github.com/helius-labs/digital-asset-validator-plugin/pull/7. 
-   Refactored the code to make this more obvious to prevent future innocent mistakes.
-   e2e tested in dev and ensured
> fix(ingester): do not ACK retryable errors

- das_api/src/api/api_impl.rs
- das_api/src/api/mod.rs
- das_api/src/main.rs
- digital_asset_types/src/dao/scopes/asset.rs
- digital_asset_types/src/dapi/signatures_for_asset.rs
- nft_ingester/src/account_updates.rs
- nft_ingester/src/main.rs
-   For decompressed assets, the `asset` table does not contain a `tree` id. So we provide optional args `tree` and `leafIndex` to query decompressed assets
-   Testing performed locally to validate the changes
> feat: add optional args `tree` and `leafIndex` for decompressed assets

- nft_ingester/Cargo.lock
- nft_ingester/src/program_transformers/token_metadata/v1_asset.rs
-   Previously, if we tried to index a reg NFT which wasn't previously indexed, it'd return the error: `StorageWriteError("Execution Error: error returned from database: null value in column \"specification_version\" of relation \"asset\" violates not-null constraint")`. This PR fixes this.
-   Testing performed to validate the changes.
> fix: indexing burnt ACC updates

- das_api/src/api/api_impl.rs
- das_api/src/api/mod.rs
- das_api/src/builder.rs
-   Handle optional args more gracefully. It'll tell you which arg was unexpected if you make a typo.
-   Local
> fix(api): improve optional payload handling for getAsset

- das_api/src/api/api_impl.rs
- das_api/src/config.rs
- das_api/src/feature_flag.rs
- das_api/src/main.rs
- digital_asset_types/src/dao/scopes/asset.rs
- digital_asset_types/src/dapi/assets_by_authority.rs
- digital_asset_types/src/dapi/assets_by_creator.rs
- digital_asset_types/src/dapi/assets_by_group.rs
- digital_asset_types/src/dapi/assets_by_owner.rs
- digital_asset_types/src/dapi/common/asset.rs
- digital_asset_types/src/dapi/search_assets.rs
- digital_asset_types/src/rpc/response.rs
- Executes another `COUNT` query to get the total assets matching the query.
- The name for the field is TBD.
- Queries parallelized.
- Feature flag added to toggle this feature on/off via env var.
- The `grand_total` field is disabled from the response fields until we finalize the change.
- Testing performed locally to validate the response.
- Testing performed locally with several ~20k leaf trees (max ~60k records) to gauge performance impacts. The impact on response time is negligible.
- More testing is necessary on dev/devnet to measure db load changes, connection usage, tail latency, etc.
> feat: add `total` number of assets that match the query

- das_api/src/api/api_impl.rs
- das_api/src/api/mod.rs
- das_api/src/config.rs
- das_api/src/feature_flag.rs
- digital_asset_types/src/dao/scopes/asset.rs
- digital_asset_types/src/dapi/common/asset.rs
- digital_asset_types/src/dapi/search_assets.rs
- digital_asset_types/src/rpc/asset.rs
- Only when both of the following are enabled, `collection_metadata` is returned:
- `APP_ENABLE_COLLECTION_METADATA` feature flag
- the `showCollectionMetadata` field in `searchAssets` method
- Only `searchAssets` method returns collection_metadata for now
- Testing done locally to validate changes
> feat: return `collection_metadata` in grouping info

- das_api/src/api/api_impl.rs
-   Temporary hack to reduce the load on the system
-   Tested locally
> das-api: Don't allow query to run if the collection has more than 100k nfts and sorting is present

- das_api/Cargo.lock
- das_api/Cargo.toml
- digital_asset_types/Cargo.lock
- digital_asset_types/Cargo.toml
- digital_asset_types/tests/common.rs
- migration/Cargo.lock
- migration/Cargo.toml
- nft_ingester/Cargo.lock
- nft_ingester/Cargo.toml
- nft_ingester/src/backfiller.rs
- nft_ingester/src/config.rs
- nft_ingester/src/program_transformers/bubblegum/collection_verification.rs
- nft_ingester/src/program_transformers/bubblegum/db.rs
- nft_ingester/src/program_transformers/bubblegum/mint_v1.rs
- nft_ingester/src/program_transformers/bubblegum/mod.rs
- nft_ingester/src/program_transformers/mod.rs
- rust-toolchain.toml
- tools/bgtask_creator/Cargo.lock
-   cNFTs can be minted without metadata. Allow it.
-   Use metaplex packages for simplicity and upgrade to 1.16.x so we are aligned with metaplex
-   helius prod, although 1.16.x changes have not been tested yet.
> fix: allow no metadata for cnft mints

- das_api/src/api/api_impl.rs
- das_api/src/api/mod.rs
- das_api/src/validation.rs
- digital_asset_types/src/dao/mod.rs
- digital_asset_types/tests/common.rs
Adds an optional new `name` query parameter to the `searchAssets` method. This parameter _must_ be used in conjunction with an owner address filter and adds a new condition and relational join for a _partial_ match on assets' `RawName` data column.
> `searchAssets`: add raw name + owner address query parameter support

- das_api/src/api/api_impl.rs
- das_api/src/api/mod.rs
- das_api/src/builder.rs
- das_api/src/error.rs
- das_api/src/feature_flag.rs
- digital_asset_types/src/dao/mod.rs
- digital_asset_types/src/dao/scopes/asset.rs
- digital_asset_types/src/dapi/assets_by_authority.rs
- digital_asset_types/src/dapi/assets_by_creator.rs
- digital_asset_types/src/dapi/assets_by_group.rs
- digital_asset_types/src/dapi/assets_by_owner.rs
- digital_asset_types/src/dapi/change_logs.rs
- digital_asset_types/src/dapi/common/asset.rs
- digital_asset_types/src/dapi/get_asset.rs
- digital_asset_types/src/dapi/search_assets.rs
- digital_asset_types/src/dapi/signatures_for_asset.rs
- digital_asset_types/src/feature_flag.rs
- digital_asset_types/src/lib.rs
- digital_asset_types/src/rpc/asset.rs
- digital_asset_types/src/rpc/display_options.rs
- digital_asset_types/src/rpc/filter.rs
- digital_asset_types/src/rpc/mod.rs
- digital_asset_types/src/rpc/response.rs
- digital_asset_types/tests/json_parsing.rs
- migration/Cargo.lock
- migration/Cargo.toml
- Add a new param `displayOptions` which can be used to opt-in for additional info.
- Allow users to see unverified collections via `displayOptions` opt-in. Also, getAssetsByGroup will return unverified collections if this flag is set.
- Add two new endpoints: `getAssetBatch` and `getAssetProofBatch`.
- New cursor-based keyset pagination method. The cursor is the same as the asset ID and behaves like the after option. When specified without any page options, it defaults to the cursor.
- Add `token_standard` in DAS response.
> feat: displayOptions + batch endpoints + keyset pagination + token_standard
