helius-labs/digital-asset-rpc-infrastructure

das_api/src/api/api_impl.rs, digital_asset_types/src/dao/scopes/asset.rs, digital_asset_types/src/dapi/assets_by_creator.rs, tests/acc_forwarder/README.md
* The SQL was querying for "creator = X OR supply > 0" instead of "creator = X AND supply >0"
* I removed the multiple creators from the query since we only ever feed a single creator to the method. Simpler code = less likely for bugs.
Tested e2e in dev on mainnet data.
=> Fix GetAssetsByCreator query

Api.Dockerfile, Ingest.Dockerfile, Load.Dockerfile, nft_ingester/src/program_transformers/token_metadata/v1_asset.rs, tests/acc_forwarder/src/main.rs
Rebased on top of the supply 0 bug
Fixes bug where creators are not being indexed if new.
Changes remove unnecessary logic, indexing creators is now a simple upsert.
=> Das creators bug

das_api/src/api/api_impl.rs
Tested locally and for all api's supporting page option
=> das: error if the page is 0

migration/src/lib.rs, migration/src/m20230510_183736_add_indices_to_assets.rs
Tested in dev. Will post the results in slack
=> DAS: Create migration to index assets tables

das_api/src/api/api_impl.rs, das_api/src/main.rs, digital_asset_types/src/dao/full_asset.rs, digital_asset_types/src/dao/mod.rs, digital_asset_types/src/dapi/assets_by_creator.rs, digital_asset_types/src/dapi/assets_by_group.rs, digital_asset_types/src/dapi/assets_by_owner.rs, digital_asset_types/src/dapi/common/asset.rs, digital_asset_types/src/dapi/search_assets.rs, digital_asset_types/src/rpc/asset.rs
Fix and suppress some compiler warnings. Ideally we want to fix all the warnings but I don't want to meddle with it too much right now.
=> das-api: fix or suppress compiler warnings

digital_asset_types/src/dapi/common/asset.rs
Even if the metadata for files are present, because of nested options, it induced bugs where the option within the option was checked which was not was expected. This fixes the parsing issue.
=> fix file parsing bug

nft_ingester/src/error/mod.rs, nft_ingester/src/tasks/mod.rs, tools/bgtask_creator/src/main.rs
- Label the network error correctly
- Retrieve and log the http related error
- Add ignore option to bg-task creator
=> background indexer improvements

tools/acc_forwarder/Cargo.lock, tools/acc_forwarder/Cargo.toml, tools/acc_forwarder/src/main.rs, tools/tree-status/Cargo.toml, tools/tree-status/src/main.rs, tools/txn_forwarder/Cargo.lock, tools/txn_forwarder/Cargo.toml, tools/txn_forwarder/src/lib.rs, tools/txn_forwarder/src/main.rs
=> Tooling improvements

nft_ingester/src/account_updates.rs, nft_ingester/src/main.rs, nft_ingester/src/metrics.rs, nft_ingester/src/program_transformers/mod.rs, nft_ingester/src/transaction_notifications.rs, tools/txn_forwarder/README.md
* Log the txn signature when we fail to index a txn
* Local, made sure it logs for forcing an error.
=> fix(ingester): log bubblegum indexing errors

tools/txn_forwarder/src/lib.rs, tools/txn_forwarder/src/main.rs
Thank you for taking the time to make an enhancement or bug fix to the digital asset validator rpc repo.
To ensure a quality PR experience this call may be recorded. Just Kidding, but we do expect a few things.
1. The Name of the PR will show up in the changelog so make it a good one, we will rename PRs or reject based on the name.
2. Please make the PR as small as possible to achieve the bugfix or feature. Big prs often are scary and hard to review.
3. Be kind to your reviewers 🤓
4. Add a good description, so we can see what the PR is all about without investing the time in the code review. We will often review code at a certain time in the day and having a list if important prs to review helps us move that along.
=> Default to replaying backward

tools/tree-status/Cargo.lock, tools/tree-status/Cargo.toml, tools/tree-status/src/main.rs, tools/txn_forwarder/README.md
See title.
Tested locally against prod.
=> feat(tree-staus): make tree fixer concurrent

tools/tree-status/src/main.rs, tools/txn_forwarder/retry.sh
Merge seq ranges to reduce getSigs overhead and improve perf.
=> fix(tools): improve performance of tree fixer

README.md, digital_asset_types/src/dapi/common/asset.rs
=> Fix: external_url returns valid url instead of null

nft_ingester/src/program_transformers/token_metadata/mod.rs, nft_ingester/src/program_transformers/token_metadata/v1_asset.rs, tools/acc_forwarder/README.md
-   Allow empty json uris. For example: https://explorer.solana.com/address/t8nGUrFQozLtgiqnc5Pu8yiodbrJCaFyE3CGeubAvky
-   Tested against that NFT and NFTs with JSON uris locally
=> fix(ingester): allow empty json uris

tools/tree-status/src/main.rs
-  Allow before and until txns to be optional 
-   Tested on couple of trees
=> tree-status: allow before/until txn to be an option

nft_ingester/src/program_transformers/token/mod.rs
-   Intermediate PR to determine the cause of lock spikes
-   Tested locally on some 1000 odd accounts.
=> das-ingester: Add metrics to figure out token account stats

digital_asset_types/src/dao/mod.rs
-   Previously, if `creatorAddress` was not specified, the `creatorVerified` field was ignored. This PR fixes this issue.
=> fix: `creatorVerified` is not ignored if `creatorAddress` is not specified

nft_ingester/src/program_transformers/token/mod.rs
-   Keep the stats to measure if the number of updates has reduced. Remove it before pushing to mainnet 
-   Tested locally
=> das: skip update if there's no change

nft_ingester/src/program_transformers/token/mod.rs
-   There's no need to do this anymore
=> Revert the code to join asset_data when indexing token account

nft_ingester/src/program_transformers/bubblegum/burn.rs, nft_ingester/src/program_transformers/bubblegum/cancel_redeem.rs, nft_ingester/src/program_transformers/bubblegum/collection_verification.rs, nft_ingester/src/program_transformers/bubblegum/creator_verification.rs, nft_ingester/src/program_transformers/bubblegum/db.rs, nft_ingester/src/program_transformers/bubblegum/delegate.rs, nft_ingester/src/program_transformers/bubblegum/mod.rs, nft_ingester/src/program_transformers/bubblegum/redeem.rs, nft_ingester/src/program_transformers/bubblegum/transfer.rs, tools/txn_forwarder/README.md
-   Fix broken redeem txn indexing
-   Locally against the following asset `444uaK1XpYyvhM4uJC1Cpox1pTkqVFYKezMx87cYzhSa` and tree `4dVaNGqsEZet56kEFnGPYbWoYv5HKGp5FpSdZZNfcm4c`
-   Tested via integ test suite too
=> fix(ingester): handle redeem txns

nft_ingester/src/error/mod.rs, nft_ingester/src/metrics.rs, nft_ingester/src/program_transformers/bubblegum/mint_v1.rs, nft_ingester/src/program_transformers/token_metadata/v1_asset.rs
-   Added metric for both transaction and account indexing 
-   Tested locally
=> Add metrics for transaction and account indexing db error

digital_asset_types/src/dapi/common/asset.rs, digital_asset_types/tests/json_parsing.rs
-   see title
-   e2e local testing for different nfts + unit tests
=> feat: add image and animation_url to links

README.md, digital_asset_types/src/dao/mod.rs, nft_ingester/src/error/mod.rs, nft_ingester/src/tasks/mod.rs
Reverts helius-labs/digital-asset-rpc-infrastructure#83
=> Revert "feat(das): add metric for task queue depth"

nft_ingester/src/error/mod.rs, nft_ingester/src/metrics.rs, nft_ingester/src/program_transformers/bubblegum/mint_v1.rs, nft_ingester/src/program_transformers/token_metadata/v1_asset.rs
Reverts helius-labs/digital-asset-rpc-infrastructure#68
=> Revert "Add metrics for transaction and account indexing db error"

nft_ingester/src/account_updates.rs, nft_ingester/src/metrics.rs, nft_ingester/src/transaction_notifications.rs
=> Das: Log account pubkey in error logs

nft_ingester/src/account_updates.rs, nft_ingester/src/metrics.rs, nft_ingester/src/transaction_notifications.rs
Reverts helius-labs/digital-asset-rpc-infrastructure#87
=> Revert "Das: Log account pubkey in error logs"

nft_ingester/src/program_transformers/token/mod.rs
=> fix: local metrics

tools/bgtask_creator/Cargo.lock, tools/bgtask_creator/README.md, tools/bgtask_creator/src/main.rs
=> fix(tools): add find command and allow creation for cNFTs

nft_ingester/src/config.rs, nft_ingester/src/main.rs, nft_ingester/src/tasks/common/mod.rs, nft_ingester/src/tasks/mod.rs
Allow bg task runner constants to be configured. 
Tested in dev
=> Support config for background task runner

nft_ingester/Cargo.lock, nft_ingester/src/program_transformers/bubblegum/creator_verification.rs, nft_ingester/src/program_transformers/bubblegum/mint_v1.rs, tools/bgtask_creator/Cargo.lock
-   Update the data/creator hash when the creators change.
-   Depends on https://github.com/helius-labs/blockbuster/pull/1 (must be ingested together)
-   Locally with regular mints + this verifyCreator txn: "3x9ciwFMjtNcjp5es8icppiaAW7SR4y4uKUsoKfQ3oRLLodQnTyVn8NcbdKAHjYJTve1wzRjAXiUQYbGV5NXmSjf"
=> fix: creator indexing

nft_ingester/src/program_transformers/bubblegum/db.rs
-   Self-explanatory. We probably want a macro if we make this configurable because otherwise passing around the bool everywhere would be annoying.
-   N/A
=> fix(ingester): do not update backfiller

nft_ingester/Cargo.lock, tools/bgtask_creator/Cargo.lock, tools/bgtask_creator/README.md, tools/bgtask_creator/src/main.rs
-   Add an option to force re-index offchain. Useful for reveals. 
-   Didn't have time to refactor "show". I never use it really, didn't feel worth the time.
-   Ran it.
=> fix(bgtask_creator): add force reindex option

das_api/Cargo.lock, das_api/Cargo.toml, das_api/src/api/api_impl.rs, das_api/src/error.rs, das_api/src/main.rs, digital_asset_types/src/dao/scopes/asset.rs, digital_asset_types/src/dapi/assets_by_group.rs, digital_asset_types/src/dapi/common/asset.rs, digital_asset_types/src/rpc/filter.rs, nft_ingester/Cargo.lock, tools/bgtask_creator/Cargo.lock
=> add option to remove sorting

nft_ingester/src/program_transformers/token_metadata/v1_asset.rs
=> Fix collection updates for regular nfts

digital_asset_types/src/dapi/common/asset.rs
-   Add `token_standard` info to asset response
-   Testing performed locally to validate the changes
=> feat: add `token_standard` to asset response
